# PyWebCrawler

## 报错

Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF)")))

Failed to establish a new connection: [Errno 65] No route to host')

Caused by SSLError(SSLError("bad handshake: SysCallError(60, 'ETIMEDOUT')")
